version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.GitTag={{.Version}} -X main.GitCommitHash={{.ShortCommit}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: i386
    tags:
      - osusergo
      - netgo

archives:
  - format: tar.gz
    files:
      - readme.md
      - server.md
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

dockers:
  - image_templates:
      - "ghcr.io/kartverket/skipctl:{{ .Tag }}-linux-amd64"
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
    goos: linux
    goarch: amd64
  - image_templates:
      - "ghcr.io/kartverket/skipctl:{{ .Tag }}-linux-arm64"
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
    goos: linux
    goarch: arm64

docker_manifests:
  - name_template: "ghcr.io/kartverket/skipctl:{{ .Tag }}"
    image_templates:
      - "ghcr.io/kartverket/skipctl:{{ .Tag }}-linux-arm64"
      - "ghcr.io/kartverket/skipctl:{{ .Tag }}-linux-amd64"

docker_signs:
  - artifacts: all
    cmd: cosign
    args:
      - "sign"
      - "--oidc-issuer=https://token.actions.githubusercontent.com"
      - "${artifact}"
      - "--yes"

signs:
  - artifacts: all
    cmd: cosign
    signature: "${artifact}.sig"
    args:
      - "sign-blob"
      - "--oidc-issuer=https://token.actions.githubusercontent.com"
      - "--output-signature=${signature}"
      - "${artifact}"
      - "--yes"

sboms:
  - artifacts: archive

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
