# nonk8s
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "skipctl"
  tags:
  - "internal"
spec:
  type: "service"
  lifecycle: "production"
  owner: "skip"
  system: "skip"
---
apiVersion: "backstage.io/v1alpha1"
kind: "Group"
metadata:
  name: "security_champion_skipctl"
  title: "Security Champion skipctl"
spec:
  type: "security_champion"
  parent: "it_security_champions"
  members:
  - "omaen"
  children:
  - "resource:skipctl"
---
apiVersion: "backstage.io/v1alpha1"
kind: "Resource"
metadata:
  name: "skipctl"
  links:
  - url: "https://github.com/kartverket/skipctl"
    title: "skipctl på GitHub"
spec:
  type: "repo"
  owner: "security_champion_skipctl"
  dependencyOf:
  - "component:skipctl"
