# nonk8s
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "skipctl"
  tags:
  - "internal"
spec:
  type: "service"
  lifecycle: "production"
  owner: "skip"
  system: "skip"
---
apiVersion: "backstage.io/v1alpha1"
kind: "Resource"
metadata:
  name: "skipctl"
  links:
  - url: "https://github.com/kartverket/skipctl"
    title: "skipctl på GitHub"
spec:
  type: "repo"
  dependencyOf:
  - "component:skipctl"
