// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: api/v1/ai_service.proto

package apiv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for streaming file upload
type AnalyzeFileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// File chunk data
	Chunk []byte `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	// File name (sent in first chunk)
	FileName string `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	// MIME type (sent in first chunk)
	MimeType string `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	// Analysis prompt (sent in first chunk)
	Prompt        string `protobuf:"bytes,4,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeFileRequest) Reset() {
	*x = AnalyzeFileRequest{}
	mi := &file_api_v1_ai_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeFileRequest) ProtoMessage() {}

func (x *AnalyzeFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ai_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeFileRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeFileRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_ai_service_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyzeFileRequest) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *AnalyzeFileRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *AnalyzeFileRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *AnalyzeFileRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

// Response message for file analysis
type AnalyzeFileResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// AI-generated response
	Response      string `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeFileResponse) Reset() {
	*x = AnalyzeFileResponse{}
	mi := &file_api_v1_ai_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeFileResponse) ProtoMessage() {}

func (x *AnalyzeFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ai_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeFileResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeFileResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_ai_service_proto_rawDescGZIP(), []int{1}
}

func (x *AnalyzeFileResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

var File_api_v1_ai_service_proto protoreflect.FileDescriptor

const file_api_v1_ai_service_proto_rawDesc = "" +
	"\n" +
	"\x17api/v1/ai_service.proto\x12\x06api.v1\"|\n" +
	"\x12AnalyzeFileRequest\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\fR\x05chunk\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x1b\n" +
	"\tmime_type\x18\x03 \x01(\tR\bmimeType\x12\x16\n" +
	"\x06prompt\x18\x04 \x01(\tR\x06prompt\"1\n" +
	"\x13AnalyzeFileResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\tR\bresponse2U\n" +
	"\tAIService\x12H\n" +
	"\vAnalyzeFile\x12\x1a.api.v1.AnalyzeFileRequest\x1a\x1b.api.v1.AnalyzeFileResponse(\x01B\x8c\x01\n" +
	"\n" +
	"com.api.v1B\x0eAiServiceProtoP\x01Z5github.com/kartverket/skipctl/pkg/api/v1/api/v1;apiv1\xa2\x02\x03AXX\xaa\x02\x06Api.V1\xca\x02\x06Api\\V1\xe2\x02\x12Api\\V1\\GPBMetadata\xea\x02\aApi::V1b\x06proto3"

var (
	file_api_v1_ai_service_proto_rawDescOnce sync.Once
	file_api_v1_ai_service_proto_rawDescData []byte
)

func file_api_v1_ai_service_proto_rawDescGZIP() []byte {
	file_api_v1_ai_service_proto_rawDescOnce.Do(func() {
		file_api_v1_ai_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_ai_service_proto_rawDesc), len(file_api_v1_ai_service_proto_rawDesc)))
	})
	return file_api_v1_ai_service_proto_rawDescData
}

var file_api_v1_ai_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_v1_ai_service_proto_goTypes = []any{
	(*AnalyzeFileRequest)(nil),  // 0: api.v1.AnalyzeFileRequest
	(*AnalyzeFileResponse)(nil), // 1: api.v1.AnalyzeFileResponse
}
var file_api_v1_ai_service_proto_depIdxs = []int32{
	0, // 0: api.v1.AIService.AnalyzeFile:input_type -> api.v1.AnalyzeFileRequest
	1, // 1: api.v1.AIService.AnalyzeFile:output_type -> api.v1.AnalyzeFileResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_v1_ai_service_proto_init() }
func file_api_v1_ai_service_proto_init() {
	if File_api_v1_ai_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_ai_service_proto_rawDesc), len(file_api_v1_ai_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_ai_service_proto_goTypes,
		DependencyIndexes: file_api_v1_ai_service_proto_depIdxs,
		MessageInfos:      file_api_v1_ai_service_proto_msgTypes,
	}.Build()
	File_api_v1_ai_service_proto = out.File
	file_api_v1_ai_service_proto_goTypes = nil
	file_api_v1_ai_service_proto_depIdxs = nil
}
