// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/api/v1/ai_service.proto

package apiv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for streaming file upload
type RefactorToArgokitv2Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// File chunk data
	Chunk []byte `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	// File name (sent in first chunk)
	FileName string `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	// MIME type (sent in first chunk)
	MimeType string `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	// Analysis prompt (sent in first chunk)
	Prompt        string `protobuf:"bytes,4,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefactorToArgokitv2Request) Reset() {
	*x = RefactorToArgokitv2Request{}
	mi := &file_proto_api_v1_ai_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefactorToArgokitv2Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefactorToArgokitv2Request) ProtoMessage() {}

func (x *RefactorToArgokitv2Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_v1_ai_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefactorToArgokitv2Request.ProtoReflect.Descriptor instead.
func (*RefactorToArgokitv2Request) Descriptor() ([]byte, []int) {
	return file_proto_api_v1_ai_service_proto_rawDescGZIP(), []int{0}
}

func (x *RefactorToArgokitv2Request) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *RefactorToArgokitv2Request) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *RefactorToArgokitv2Request) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *RefactorToArgokitv2Request) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

// Response message for file analysis
type RefactorToArgokitv2Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// AI-generated response
	Response      string `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefactorToArgokitv2Response) Reset() {
	*x = RefactorToArgokitv2Response{}
	mi := &file_proto_api_v1_ai_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefactorToArgokitv2Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefactorToArgokitv2Response) ProtoMessage() {}

func (x *RefactorToArgokitv2Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_v1_ai_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefactorToArgokitv2Response.ProtoReflect.Descriptor instead.
func (*RefactorToArgokitv2Response) Descriptor() ([]byte, []int) {
	return file_proto_api_v1_ai_service_proto_rawDescGZIP(), []int{1}
}

func (x *RefactorToArgokitv2Response) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

var File_proto_api_v1_ai_service_proto protoreflect.FileDescriptor

const file_proto_api_v1_ai_service_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/api/v1/ai_service.proto\x12\x06api.v1\"\x84\x01\n" +
	"\x1aRefactorToArgokitv2Request\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\fR\x05chunk\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x1b\n" +
	"\tmime_type\x18\x03 \x01(\tR\bmimeType\x12\x16\n" +
	"\x06prompt\x18\x04 \x01(\tR\x06prompt\"9\n" +
	"\x1bRefactorToArgokitv2Response\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\tR\bresponse2m\n" +
	"\tAIService\x12`\n" +
	"\x13RefactorToArgokitv2\x12\".api.v1.RefactorToArgokitv2Request\x1a#.api.v1.RefactorToArgokitv2Response(\x01B0Z.github.com/kartverket/skipctl/pkg/api/v1;apiv1b\x06proto3"

var (
	file_proto_api_v1_ai_service_proto_rawDescOnce sync.Once
	file_proto_api_v1_ai_service_proto_rawDescData []byte
)

func file_proto_api_v1_ai_service_proto_rawDescGZIP() []byte {
	file_proto_api_v1_ai_service_proto_rawDescOnce.Do(func() {
		file_proto_api_v1_ai_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_api_v1_ai_service_proto_rawDesc), len(file_proto_api_v1_ai_service_proto_rawDesc)))
	})
	return file_proto_api_v1_ai_service_proto_rawDescData
}

var file_proto_api_v1_ai_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_api_v1_ai_service_proto_goTypes = []any{
	(*RefactorToArgokitv2Request)(nil),  // 0: api.v1.RefactorToArgokitv2Request
	(*RefactorToArgokitv2Response)(nil), // 1: api.v1.RefactorToArgokitv2Response
}
var file_proto_api_v1_ai_service_proto_depIdxs = []int32{
	0, // 0: api.v1.AIService.RefactorToArgokitv2:input_type -> api.v1.RefactorToArgokitv2Request
	1, // 1: api.v1.AIService.RefactorToArgokitv2:output_type -> api.v1.RefactorToArgokitv2Response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_api_v1_ai_service_proto_init() }
func file_proto_api_v1_ai_service_proto_init() {
	if File_proto_api_v1_ai_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_api_v1_ai_service_proto_rawDesc), len(file_proto_api_v1_ai_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_api_v1_ai_service_proto_goTypes,
		DependencyIndexes: file_proto_api_v1_ai_service_proto_depIdxs,
		MessageInfos:      file_proto_api_v1_ai_service_proto_msgTypes,
	}.Build()
	File_proto_api_v1_ai_service_proto = out.File
	file_proto_api_v1_ai_service_proto_goTypes = nil
	file_proto_api_v1_ai_service_proto_depIdxs = nil
}
