// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: api/v1/diagnostic.proto

package apiv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Do a ping for a given hostname
type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3,oneof" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_api_v1_diagnostic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_diagnostic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_diagnostic_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *PingRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *PingRequest) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

// Results of the ping test
type PingResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Pingable             bool                   `protobuf:"varint,1,opt,name=pingable,proto3" json:"pingable,omitempty"`
	PacketsReceived      int32                  `protobuf:"varint,2,opt,name=packets_received,json=packetsReceived,proto3" json:"packets_received,omitempty"`
	PacketsSent          int32                  `protobuf:"varint,3,opt,name=packets_sent,json=packetsSent,proto3" json:"packets_sent,omitempty"`
	PacketLossPercentage int32                  `protobuf:"varint,4,opt,name=packet_loss_percentage,json=packetLossPercentage,proto3" json:"packet_loss_percentage,omitempty"`
	PingedHost           string                 `protobuf:"bytes,5,opt,name=pinged_host,json=pingedHost,proto3" json:"pinged_host,omitempty"`
	MinRtt               *durationpb.Duration   `protobuf:"bytes,6,opt,name=min_rtt,json=minRtt,proto3" json:"min_rtt,omitempty"`
	MaxRtt               *durationpb.Duration   `protobuf:"bytes,7,opt,name=max_rtt,json=maxRtt,proto3" json:"max_rtt,omitempty"`
	AvgRtt               *durationpb.Duration   `protobuf:"bytes,8,opt,name=avg_rtt,json=avgRtt,proto3" json:"avg_rtt,omitempty"`
	StdDevRtt            *durationpb.Duration   `protobuf:"bytes,9,opt,name=std_dev_rtt,json=stdDevRtt,proto3" json:"std_dev_rtt,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_api_v1_diagnostic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_diagnostic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_diagnostic_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetPingable() bool {
	if x != nil {
		return x.Pingable
	}
	return false
}

func (x *PingResponse) GetPacketsReceived() int32 {
	if x != nil {
		return x.PacketsReceived
	}
	return 0
}

func (x *PingResponse) GetPacketsSent() int32 {
	if x != nil {
		return x.PacketsSent
	}
	return 0
}

func (x *PingResponse) GetPacketLossPercentage() int32 {
	if x != nil {
		return x.PacketLossPercentage
	}
	return 0
}

func (x *PingResponse) GetPingedHost() string {
	if x != nil {
		return x.PingedHost
	}
	return ""
}

func (x *PingResponse) GetMinRtt() *durationpb.Duration {
	if x != nil {
		return x.MinRtt
	}
	return nil
}

func (x *PingResponse) GetMaxRtt() *durationpb.Duration {
	if x != nil {
		return x.MaxRtt
	}
	return nil
}

func (x *PingResponse) GetAvgRtt() *durationpb.Duration {
	if x != nil {
		return x.AvgRtt
	}
	return nil
}

func (x *PingResponse) GetStdDevRtt() *durationpb.Duration {
	if x != nil {
		return x.StdDevRtt
	}
	return nil
}

type PortProbeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Hostname or IP
	Host          string               `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Timeout       *durationpb.Duration `protobuf:"bytes,3,opt,name=timeout,proto3,oneof" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortProbeRequest) Reset() {
	*x = PortProbeRequest{}
	mi := &file_api_v1_diagnostic_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortProbeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortProbeRequest) ProtoMessage() {}

func (x *PortProbeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_diagnostic_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortProbeRequest.ProtoReflect.Descriptor instead.
func (*PortProbeRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_diagnostic_proto_rawDescGZIP(), []int{2}
}

func (x *PortProbeRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *PortProbeRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *PortProbeRequest) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type PortProbeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Open          bool                   `protobuf:"varint,1,opt,name=open,proto3" json:"open,omitempty"`
	AddrProbed    *string                `protobuf:"bytes,2,opt,name=addr_probed,json=addrProbed,proto3,oneof" json:"addr_probed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortProbeResponse) Reset() {
	*x = PortProbeResponse{}
	mi := &file_api_v1_diagnostic_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortProbeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortProbeResponse) ProtoMessage() {}

func (x *PortProbeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_diagnostic_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortProbeResponse.ProtoReflect.Descriptor instead.
func (*PortProbeResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_diagnostic_proto_rawDescGZIP(), []int{3}
}

func (x *PortProbeResponse) GetOpen() bool {
	if x != nil {
		return x.Open
	}
	return false
}

func (x *PortProbeResponse) GetAddrProbed() string {
	if x != nil && x.AddrProbed != nil {
		return *x.AddrProbed
	}
	return ""
}

var File_api_v1_diagnostic_proto protoreflect.FileDescriptor

const file_api_v1_diagnostic_proto_rawDesc = "" +
	"\n" +
	"\x17api/v1/diagnostic.proto\x12\x06api.v1\x1a\x1egoogle/protobuf/duration.proto\"}\n" +
	"\vPingRequest\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x128\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationH\x00R\atimeout\x88\x01\x01B\n" +
	"\n" +
	"\b_timeout\"\xa6\x03\n" +
	"\fPingResponse\x12\x1a\n" +
	"\bpingable\x18\x01 \x01(\bR\bpingable\x12)\n" +
	"\x10packets_received\x18\x02 \x01(\x05R\x0fpacketsReceived\x12!\n" +
	"\fpackets_sent\x18\x03 \x01(\x05R\vpacketsSent\x124\n" +
	"\x16packet_loss_percentage\x18\x04 \x01(\x05R\x14packetLossPercentage\x12\x1f\n" +
	"\vpinged_host\x18\x05 \x01(\tR\n" +
	"pingedHost\x122\n" +
	"\amin_rtt\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\x06minRtt\x122\n" +
	"\amax_rtt\x18\a \x01(\v2\x19.google.protobuf.DurationR\x06maxRtt\x122\n" +
	"\aavg_rtt\x18\b \x01(\v2\x19.google.protobuf.DurationR\x06avgRtt\x129\n" +
	"\vstd_dev_rtt\x18\t \x01(\v2\x19.google.protobuf.DurationR\tstdDevRtt\"\x80\x01\n" +
	"\x10PortProbeRequest\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x128\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationH\x00R\atimeout\x88\x01\x01B\n" +
	"\n" +
	"\b_timeout\"]\n" +
	"\x11PortProbeResponse\x12\x12\n" +
	"\x04open\x18\x01 \x01(\bR\x04open\x12$\n" +
	"\vaddr_probed\x18\x02 \x01(\tH\x00R\n" +
	"addrProbed\x88\x01\x01B\x0e\n" +
	"\f_addr_probed2\x8c\x01\n" +
	"\x11DiagnosticService\x123\n" +
	"\x04Ping\x12\x13.api.v1.PingRequest\x1a\x14.api.v1.PingResponse\"\x00\x12B\n" +
	"\tPortProbe\x12\x18.api.v1.PortProbeRequest\x1a\x19.api.v1.PortProbeResponse\"\x00B\x8d\x01\n" +
	"\n" +
	"com.api.v1B\x0fDiagnosticProtoP\x01Z5github.com/kartverket/skipctl/pkg/api/v1/api/v1;apiv1\xa2\x02\x03AXX\xaa\x02\x06Api.V1\xca\x02\x06Api\\V1\xe2\x02\x12Api\\V1\\GPBMetadata\xea\x02\aApi::V1b\x06proto3"

var (
	file_api_v1_diagnostic_proto_rawDescOnce sync.Once
	file_api_v1_diagnostic_proto_rawDescData []byte
)

func file_api_v1_diagnostic_proto_rawDescGZIP() []byte {
	file_api_v1_diagnostic_proto_rawDescOnce.Do(func() {
		file_api_v1_diagnostic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_diagnostic_proto_rawDesc), len(file_api_v1_diagnostic_proto_rawDesc)))
	})
	return file_api_v1_diagnostic_proto_rawDescData
}

var file_api_v1_diagnostic_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_v1_diagnostic_proto_goTypes = []any{
	(*PingRequest)(nil),         // 0: api.v1.PingRequest
	(*PingResponse)(nil),        // 1: api.v1.PingResponse
	(*PortProbeRequest)(nil),    // 2: api.v1.PortProbeRequest
	(*PortProbeResponse)(nil),   // 3: api.v1.PortProbeResponse
	(*durationpb.Duration)(nil), // 4: google.protobuf.Duration
}
var file_api_v1_diagnostic_proto_depIdxs = []int32{
	4, // 0: api.v1.PingRequest.timeout:type_name -> google.protobuf.Duration
	4, // 1: api.v1.PingResponse.min_rtt:type_name -> google.protobuf.Duration
	4, // 2: api.v1.PingResponse.max_rtt:type_name -> google.protobuf.Duration
	4, // 3: api.v1.PingResponse.avg_rtt:type_name -> google.protobuf.Duration
	4, // 4: api.v1.PingResponse.std_dev_rtt:type_name -> google.protobuf.Duration
	4, // 5: api.v1.PortProbeRequest.timeout:type_name -> google.protobuf.Duration
	0, // 6: api.v1.DiagnosticService.Ping:input_type -> api.v1.PingRequest
	2, // 7: api.v1.DiagnosticService.PortProbe:input_type -> api.v1.PortProbeRequest
	1, // 8: api.v1.DiagnosticService.Ping:output_type -> api.v1.PingResponse
	3, // 9: api.v1.DiagnosticService.PortProbe:output_type -> api.v1.PortProbeResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_api_v1_diagnostic_proto_init() }
func file_api_v1_diagnostic_proto_init() {
	if File_api_v1_diagnostic_proto != nil {
		return
	}
	file_api_v1_diagnostic_proto_msgTypes[0].OneofWrappers = []any{}
	file_api_v1_diagnostic_proto_msgTypes[2].OneofWrappers = []any{}
	file_api_v1_diagnostic_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_diagnostic_proto_rawDesc), len(file_api_v1_diagnostic_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_diagnostic_proto_goTypes,
		DependencyIndexes: file_api_v1_diagnostic_proto_depIdxs,
		MessageInfos:      file_api_v1_diagnostic_proto_msgTypes,
	}.Build()
	File_api_v1_diagnostic_proto = out.File
	file_api_v1_diagnostic_proto_goTypes = nil
	file_api_v1_diagnostic_proto_depIdxs = nil
}
